---
title: "Setting up a whisper room sound booth"
description: |
  It is harder than it looks. 
date: 09-16-2018
author:
  - name: Joseph V. Casillas 
    url: https://www.jvcasillas.com
    affiliation: Rutgers University
    affiliation_url: https://www.rutgers.edu
base_url: http://www.jvcasillas.com
categories: [phonetics, soundbooth]
twitter:
  creator: "@jvcasill"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


```{r, echo=F}
library("htmltools")
library("bsplus")
```


## Packaging

```{r, echo=F}
bs_carousel(id = "soundbooth_packaging") %>%
  bs_set_data(interval = FALSE) %>%
  bs_append(content = bs_carousel_image(src = "./assets/img/01.png")) %>%
  bs_append(content = bs_carousel_image(src = "./assets/img/02.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/03.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/04.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/05.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/06.png")) 
```

## Assembly

```{r, echo=F}
bs_carousel(id = "soundbooth_assembly") %>%
  bs_set_data(interval = FALSE) %>%
  bs_append(content = bs_carousel_image(src = "./assets/img/07.png")) %>%
  #bs_append(content = bs_carousel_image(src = "./assets/img/08.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/09.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/10.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/11.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/12.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/13.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/14.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/15.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/16.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/17.png")) 
```

## Aftermath

```{r, echo=F}
bs_carousel(id = "soundbooth_cleanup") %>%
  bs_set_data(interval = FALSE) %>%
  bs_append(content = bs_carousel_image(src = "./assets/img/18.png")) %>%
  bs_append(content = bs_carousel_image(src = "./assets/img/19.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/20.png")) %>% 
  bs_append(content = bs_carousel_image(src = "./assets/img/21.png")) 
```

## Walkthrough

```{r, echo=F}
bs_carousel(id = "soundbooth_walkthrough") %>%
  bs_set_data(interval = FALSE) %>%
  bs_append(content = bs_carousel_image(src = "./assets/vids/vents.mov")) %>%
  bs_append(content = bs_carousel_image(src = "./assets/vids/inside.mov")) 
```

</br>
