---
title: ""
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
```

```{css echo=FALSE}

d-title h1 {
  font-size: 0px;
}

```


```{r, landing-img, fig.retina=2, out.width="100%", fig.asp=1, layout="l-screen", eval=F}
library("tidyverse")
library("brms")
library("tidybayes")
library("networkD3")

# mod <- brm(
#   mpg ~ drat, 
#   file = here::here("assets", "mod"), 
#   data = mtcars)

# mod_post <- mod %>% 
#   as_tibble() %>% 
#   select(intercept = b_Intercept, slope = b_drat)

# post_samp <- sample_n(mod_post, 500)
# post_avg  <- summarize(mod_post, across(c("intercept", "slope"), mean))

# mtcars %>% 
#   select(mpg, drat) %>% 
#   ggplot() + 
#   aes(x = drat, y = mpg) + 
#     geom_abline(data = post_samp, aes(intercept = intercept, slope = slope), 
#                 alpha = 0.025, color = "grey10") + 
#     geom_abline(data = post_avg, aes(intercept = intercept, slope = slope), 
#                 color = "white", size = 1.5) + 
#     geom_point(size = 1.5, color = "#cc0033") + 
#     theme_void()

data(MisLinks, MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.7)


```







<!-- particles.js container --> 
<div id="particles-js"></div> 

<!-- particles.js lib - https://github.com/VincentGarreau/particles.js --> 
<script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script> 


```{css}
/* ---- reset ---- */ body{ margin:0; font:normal 75% Arial, Helvetica, sans-serif; } canvas{ display: block; vertical-align: bottom; } /* ---- particles.js container ---- */ #particles-js{ position:absolute; width: 100%; height: 100%; background-color: #ffffff; background-image: url(""); background-repeat: no-repeat; background-size: cover; background-position: 50% 50%; } /* ---- stats.js ---- */ .count-particles{ background: #000022; position: absolute; top: 48px; left: 0; width: 80px; color: #13E8E9; font-size: .8em; text-align: left; text-indent: 4px; line-height: 14px; padding-bottom: 2px; font-family: Helvetica, Arial, sans-serif; font-weight: bold; } .js-count-particles{ font-size: 1.1em; } #stats, .count-particles{ -webkit-user-select: none; margin-top: 5px; margin-left: 5px; } #stats{ border-radius: 3px 3px 0 0; overflow: hidden; } .count-particles{ border-radius: 0 0 3px 3px; }
```

```{js}
particlesJS("particles-js", {"particles":{"number":{"value":80,"density":{"enable":true,"value_area":800}},"color":{"value":"#cc0033"},"shape":{"type":"circle","stroke":{"width":0,"color":"#000000"},"polygon":{"nb_sides":5},"image":{"src":"img/github.svg","width":100,"height":100}},"opacity":{"value":0.5,"random":false,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":3,"random":true,"anim":{"enable":false,"speed":40,"size_min":0.1,"sync":false}},"line_linked":{"enable":true,"distance":150,"color":"#4d4d4d","opacity":0.4,"width":1},"move":{"enable":true,"speed":6,"direction":"none","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":false,"rotateX":552.4044389642416,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":true,"mode":"grab"},"onclick":{"enable":true,"mode":"repulse"},"resize":true},"modes":{"grab":{"distance":400,"line_linked":{"opacity":1}},"bubble":{"distance":179.82017982017982,"size":19.98001998001998,"duration":0.959040959040959,"opacity":0.3516483516483517,"speed":3},"repulse":{"distance":223.7762237762238,"duration":0.4},"push":{"particles_nb":4},"remove":{"particles_nb":2}}},"retina_detect":true});var count_particles, stats, update; stats = new Stats; stats.setMode(0); stats.domElement.style.position = 'absolute'; stats.domElement.style.left = '0px'; stats.domElement.style.top = '0px'; document.body.appendChild(stats.domElement); count_particles = document.querySelector('.js-count-particles'); update = function() { stats.begin(); stats.end(); if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) { count_particles.innerText = window.pJSDom[0].pJS.particles.array.length; } requestAnimationFrame(update); }; requestAnimationFrame(update);;
```
