---
framework: lanyon
onefile: False
mode: selfcontained
url: {lib: ../libraries}
---

## Research

<p></p>
<div class="tabbable">
    <ul class="nav nav-tabs" id="myTab">
        <li class="active">
            <a href="#current-research" data-toggle="tab">Current research</a>
        </li>
        <li class="">
            <a href="#publications" data-toggle="tab">Publications</a>
        </li>
        <li class="">
            <a href="#presentations" data-toggle="tab">Presentations</a>
        </li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="current-research">
            <p>I am an active member of the <a alt="AAPL" href="http://aaplab1.github.io" target='_new'><span class="showtooltip" title="AAPL webpage">Arizona Applied Phonetics Laboratory</span></a> at the University of Arizona. My main interests are in phonetics, phonology. My current projects are centered on second language speech learning &amp; bilingualism. Specifically, I investigate native phonetic experience and its influence on L2 speech production, perception and lexical processing. I am also interested in how dialectal variation affects linguistic attitudes.</p>
        </div>
        <div class="tab-pane" id="publications" style="margin-left:2em;text-indent:-2em">
            <h4>Recent Publications</h4>
                <p>
			Casillas, J. V. (2012). La fricativización del africado /ʧ/ en el habla de las mujeres del sur de Arizona. <i>Divergencias: Revista de estudios lingüísticos y literarios</i>, 10 (1). 
            <a alt="Divergencias" href="http://divergencias.arizona.edu/sites/divergenciasweb.arizona.edu/files/articles/FricativizacionDivergencias.pdf" target='_new'><span class="showtooltip" title="Read paper">Link</span></a> |
            <a href="javascript:ReverseDisplay('Casillas2012Abstract')">Abstract</a> |
            <a href="javascript:ReverseDisplay('Casillas2012Bib')">Bib</a>

            <div id="Casillas2012Abstract" style="display:none;margin-left:2em;text-indent:0em">
            <p class="minip">La fricativización del fonema /ʧ/ supone uno de los procesos fonológicos más productivos del español mexicano, sin embargo, actualmente sigue siendo uno de los menos estudiados. Partiendo de las investigaciones de Cedergren (1973), Brown (1989) y Herrera (2006), el presente estudio analiza la fricativización del fonema /ʧ/ en el español de las mujeres del sur de Arizona. El uso de una regresión de subida y bajada de Goldvarb X determinó que la edad de las participantes, el contexto posterior a /ʧ/ y el lugar de nacimiento son factores determinantes para la realización de la variante fricativa.</p>
            </div>

            <div id="Casillas2012Bib" style="display:none;margin-left:2em;text-indent:-2em">
            <code>
            @article{Casillas2012, </br> 
            Author = {Joseph Vincent Casillas},  </br> 
            Journal = {Divergencias: Revista de estudios ling{\"u}{\'\i}sticos y literarios},  </br> 
            Number = {1},  </br> 
            Title = {La fricativizaci{\'o}n del africado \textipa{/\textteshlig/} en el habla de las mujeres del sur de Arizona},  </br> 
            Volume = {10},  </br> 
            Year = {2012}}
            </code>
            </div>
                </p>

                <p>
			Casillas, J. V. (2010). La vibrante múltiple intervocálica: los ejercicios de canto como ayuda a su pronunciación en español. <i>La Gaceta Hispánica de Madrid</i>, VIII.
            <a href="javascript:ReverseDisplay('Casillas2010Bib')">Bib</a>

            <div id="Casillas2010Bib" style="display:none;margin-left:2em;text-indent:-2em">
            <code>
            @article{Casillas2010, </br>
            Author = {Joseph Vincent Casillas}, </br>
            Issn = {1886-1741}, </br>
            Journal = {La Gaceta Hisp{\'a}nica de Madrid}, </br>
            Title = {La vibrante m{\'u}ltiple intervoc{\'a}lica: los ejercicios de canto como ayuda a su pronunciaci{\'o}n en espa{\~n}ol}, </br>
            Volume = {VIII}, </br>
            Year = {2010}}
            </code>
            </div>
                </p>

                <p>
			Casillas, J. V. (2009). El uso de los refranes en el quijote. <i>La Gaceta Hispánica de Madrid</i>, VIII.
            <a alt="Gaceta" href="http://gacetahispanica.com/?p=1175" target='_new'><span class="showtooltip" title="Read paper">Link</span></a> |
            <a href="javascript:ReverseDisplay('Casillas2009Abstract')">Summary</a> |
            <a href="javascript:ReverseDisplay('Casillas2009Bib')">Bib</a>

            <div id="Casillas2009Abstract" style="display:none;margin-left:2em;text-indent:0em">
            <p class="minip">El refrán es una de las partes fundamentales de la lengua castellana que vemos plasmada en toda la cultura española, tanto en el habla cotidiana como en la literatura. El refrán ha tenido y sigue teniendo suma importancia a la hora de conocer y entender la cultura hispana, ya sea oral o en textos escritos. Es algo que los estudiantes de español como segunda lengua pueden comprobar puesto que supone un reto en su aprendizaje. Como es bien sabido, El Quijote, novela estudiada exhaustivamente desde que fue publicada por primera vez, es una fuente paremiológica imprescindible para quien quiera aprender, investigar o simplemente gozar del refranero cervantino. En palabras de Tarnovska: “No hay otra obra literaria que sea ni pueda ser considerada refranero popular de la misma importancia que El Quijote” (287). Además de ser una de las obras de literatura más esenciales de todos los tiempos, también es un recurso, una vía por medio de la cual el lector puede acercarse a la cultura española.</p>
            </div>

            <div id="Casillas2009Bib" style="display:none;margin-left:2em;text-indent:-2em">
            <code>
            @article{Casillas2009, </br>
                Author = {Joseph Vincent Casillas}, </br>
                Issn = {1886-1741}, </br>
                Journal = {La Gaceta Hisp{\'a}nica de Madrid}, </br>
                Title = {El uso de los refranes en El Quijote}, </br>
                Volume = {VIII}, </br>
                Year = {2009}}
            </code>
            </div>
                </p>

            <h4>Proceedings</h4>
                <p>
            Simonet, M., Casillas, J. V., &amp; Diaz, Y. (2014). The effects of stress/accent on VOT depend on language (English, Spanish), consonant (/d/, /t/) and linguistic experience (monolinguals, bilinguals). In <i>Speech Prosody 7 - Proceedings of the 7th international conference on Speech Prosody: Social and Linguistic Speech Prosody</i>, eds. N. Campbell, D. Gibbon, &amp; D. Hirst, 202-206. Trinity College, Dublin. ISSN: 2333-2042.
            <a alt="SP7" href="http://www.speechprosody2014.org" target='_new'><span class="showtooltip" title="SP7 proceedings">Link</span></a> |
            <a href="javascript:ReverseDisplay('SimonetCasillasDiazSP72014Abstract')">Abstract</a> |
            <a href="javascript:ReverseDisplay('SimonetCasillasDiazSP72014Bib')">Bib</a>

            <div id="SimonetCasillasDiazSP72014Abstract" style="display:none;margin-left:2em;text-indent:0em">
            <p class="minip">This study examines Voice Onset Times of coronal stops in utterance-initial position in two languages. Crucially, the effects of lexical stress (stressed, unstressed syllable) on VOT are analyzed. The study investigates aspirated stops (English /t/), short-lag voiceless stops (English /d/, Spanish /t/) and prevoiced stops (Spanish /d/). Three groups of speakers provide data: English monolinguals, Spanish monolinguals, and proficient Spanish-English bilinguals. The study finds that lexical stress lengthens aspiration (English /t/) and prevoicing (Spanish /d/) but it does not alter significantly short-lag stops (Spanish /t/, English /d/). Monolinguals and bilinguals differ slightly in their phonetic behavior. Implications for gestural coordination as well as for feature theory are discussed.</p>
            </div>

            <div id="SimonetCasillasDiazSP72014Bib" style="display:none;margin-left:2em;text-indent:-2em">
            <code>
            @inproceedings{SimonetCasillasDiazSP72014, </br>
                author = {Miquel Simonet and Joseph Vincent Casillas and Yamile D\'iaz}, </br>
                Editor = {N Campbell and D Gibbon and D Hirst}, </br>
                Organization = {In Speech Prosody 7 - Proceedings of the 7th international conference on Speech Prosody: Social and Linguistic Speech Prosody}, </br>
                Publisher = {Trinity College, Dublin. speechprosody2014.org, ISSN: 2333-2042}, </br>
                Title = {The effects of stress/accent on VOT depend on language (English, Spanish), consonant (/d/, /t/) and linguistic experience (monolinguals, bilinguals)}, </br>
                Year = {2014}}
            </code>
            </div>
                </p>

                <p>
			Casillas, J. V. (2013). La fricativización del africado /ʧ/: actitudes lingüísticas cerca de la frontera. In <i>Selected Proceedings of the 6th Workshop on Spanish Sociolinguistics</i>, ed. Ana M. Carvalho and Sara Beaudrie, 177-188. Somerville, MA: Cascadilla Proceedings Project. Document #2867.
            <a alt="WSS6" href="http://www.lingref.com/cpp/wss/6/abstract2867.html" target='_new'><span class="showtooltip" title="WSS6 abstract">Link</span></a> |
            <a href="javascript:ReverseDisplay('CasillasWSS62013Abstract')">Abstract</a> |
            <a href="javascript:ReverseDisplay('CasillasWSS62013Bib')">Bib</a>

            <div id="CasillasWSS62013Abstract" style="display:none;margin-left:2em;text-indent:0em">
            <p class="minip">La presente investigación examina las actitudes lingüísticas que tienen los hablantes de español de la comunidad de habla de Tucson, Arizona hacia el dialecto sonorense. Concretamente, se investiga el efecto que tiene la realización del africado prepalatal sordo y su variante fricativa no estándar sobre las percepciones de credibilidad de 4 candidatos a un puesto de trabajo hipotético. Un cuestionario basado en los índices de credibilidad utilizados por McCroskey (1999) se distribuyó a 111 participantes para medir sus actitudes hacia los 4 candidatos. El experimento consistió en una variación de la técnica matched-guise para asignar a los participantes a uno de dos grupos, el primero escuchó la variante estándar y el segundo la variante fricativa. Se demuestra que la variante fricativa recibe valoraciones de credibilidad más bajas que la variante estándar.</p>
            </div>

            <div id="CasillasWSS62013Bib" style="display:none;margin-left:2em;text-indent:-2em">
            <code>
            @inproceedings{CasillasWSS62013, </br>
                Author = {Casillas, Joseph Vincent}, </br>
                Editor = {Ana M. Carvalho and Sara Beaudrie}, </br>
                Organization = {In Selected Proceedings of the $6^{th}$ Workshop on Spanish Sociolinguistics, ed. Ana M. Carvalho and Sara Beaudrie, 177-188}, </br>
                Publisher = {Somerville, MA: Cascadilla Proceedings Project. www.lingref.com, document \#2867}, </br>
                Title = {La fricativizaci{\'o}n del africado \textipa{/\textteshlig/}: actitudes ling{\"u}{\'\i}sticas cerca de la frontera}, </br>
                Year = {2013}}
            </code>
            </div>
                </p>

            <h4>Submitted</h4>
                <p>
			Casillas, J. V. &amp; Simonet, M. Perception and spoken-word recognition of English-specific vowel contrasts by early and late learners.
                </p>

                <p>
			Casillas, J. V. Production and perception of the English /i/-/ɪ/ vowel contrast in L2 dominant early learners of English.
                </p>

                <p>
            Casillas, J. V. El foco y el orden de palabras en español
                </p>

            <h4>In preparation</h4>

                <p>
			Casillas, J. V. Community Approaches to Translating Specialized Terminology in Linguistics: lingreference.org.
                </p>

        </div>
        <div class="tab-pane" id="presentations" style="margin-left:2em;text-indent:-2em">
            <h4>Presentations</h4>
		        <p>
            Bessett, R. M., Casillas, J. V. &amp; Ramírez Martínez, M. (2014). Language Choice and Accommodation: Casual Encounters Along the U.S. Border. <i>7th International Workshop on Spanish Sociolinguistics</i>. University of Wisconsin-Madison. Madison, Wisconsin (April, 2014).
               </p>

                <p>
			Casillas, J. V. (2013). Perception of English /i/-/ɪ/ tense/lax vowel contrast by early learners of English. <i>Second Language Research Forum (SLRF)</i>. Brigham Young University. Provo, Utah. (October, 2013).
		        </p>

                <p>
			Casillas, J. V. (2013). English-dominant early Spanish-English bilinguals production and perception of English tense lax vowel contrasts. <i>Phonetics and Phonology in Iberia</i>. Universidade de Lisboa. Lisbon, Portugal. (June, 2013).
                </p>

                <p>
			Casillas, J. V. (2012). La fricativización del africado /ʧ/: actitudes lingüísticas cerca de la frontera. <i>6th International Workshop on Spanish Sociolinguistics</i>. University of Arizona. Tucson, Arizona (April, 2012).
                </p>

                <p>
			Casillas, J. V. (2012). Los piojos, las pulgas y el canto... ¡oh my! una segunda mirada a la teoría de dunbar, el cotilleo y el papel de la música en la evolución del lenguage. <i>22nd Annual Symposium on Hispanic and Luso-Brazilian Literature, Language and Culture</i>. University of Arizona. Tucson, Arizona (February, 2012).
                </p>

                <p>
			Casillas, J. V. (2011). Going mental with vocabulary: the use of iDevice applications in the classroom. Spanish Heritage Language Program Share Day. University of Arizona. Tucson, Arizona (March, 2011).
                </p>

                <p>
			Casillas, J. V. (2011). La fricativización del africado /ʧ/ en el habla de las mujeres del sur de arizona. <i>21st Annual Symposium on Hispanic and Luso-Brazilian Literature</i>. University of Arizona. Tucson, Arizona (March, 2011).
                </p>

            <h4>Poster Presentations</h4>
                <p>
            Simonet, M., Casillas, J. V., &amp; Diaz, Y. (2014). The effects of stress/accent on VOT depend on language (English, Spanish), consonant (/d/, /t/) and linguistic experience (monolinguals, bilinguals). <i>7th international conference on Speech Prosody: Social and Linguistic Speech Prosody</i>. Trinity College, Dublin (May, 2014).
                </p>

                <p>
			Casillas, J. V. &amp; Simonet, M. (2013). English-dominant early Spanish/English bilinguals perception of English tense-lax vowel contrasts. <i>PPLC 13: Phonetics, phonology and languages in contact: Contact varieties, multilingualism, and second language learning</i>. Paris, Délégation Générale Wallonie-Bruxelles (August, 2013).
                </p>
        </div>
    </div>
</div>

<script type="text/javascript">  
        $(document).ready(function () {  
            $('.dropdown-toggle').dropdown();  
        });  
</script>
