<div class="tab-pane active" id="overview">

<h4>Overview</h4>

<p align="justify">
I am currently in the process of setting up my research laboratory at Rutgers 
University, so stay tuned for more information. I am affiliated with the 
<a alt="phonolab" href="http://rci.rutgers.edu/~phonolab/index.php" target='_new'><span class="showtooltip" title="Phonolab webpage">Phonology and Field Research Laboratory (PhonoLab)</span></a>, and I am a former member of the 
<a alt="AAPL" href="https://sites.google.com/site/miquelsimonet/sports-lab-az" target='_new'><span class="showtooltip" title="AAPL webpage">Arizona Applied Phonetics Laboratory</span></a> at the University of Arizona. 


My main interests are in phonetics, laboratory phonology, and second language 
acquisition. A principle aim of my research is to better understand the 
relationship between language use and sound representation in the mind, as well 
as the structure of sound systems in human languages. Most of my research is 
conducted on bilinguals of varying proficiency and linguistic experience. 
Feel free to explore the tabs on this page if you are interested in knowing 
more about my research projects. You can visit my academic profiles on 
researchgate, academia.edu, and google scholar by clicking on the icons below.
</p>

#### News

##### Recent/Upcoming talks
 
- HLS (Oct 2016)
- SSHL (Feb 2017)
- LSRL (April 2017)
 
##### Recent/Upcoming publications
 
- Lexically driven selective adaptation by ambiguous auditory stimuli occurs 
after limited exposure to adaptors ([JASA](http://scitation.aip.org/content/asa/journal/jasa/139/5/10.1121/1.4951704))
- Language-specific perceptual normalization in adult second language 
acquisition (Forthcoming)

<div align='center'>
<a class="twitter-timeline" data-width="300" data-height="300" data-theme="light" data-link-color="#a00" href="https://twitter.com/jvcasill"></a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

</div>


