

<!-- FOURTH TAB BEGIN-->
<div id="presentations" class="tab-pane fade" style="margin-left:2em;text-indent:-2em">
<h4>Presentations</h4>

<span class="tempTimes">




```{r, results='asis', echo=FALSE, eval=TRUE, cache=FALSE}
print(bib[key = "casillasLSRL2017morph"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "casillasLSRL2017"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "casillasSSHL2017"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasHLS2016"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "SimonetCasillasOsborneSOUNDWORD2016"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasDiazSimonetHLS2015"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "BessettCasillasMartinezWSS72014conf"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasSLRF2013"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasPAPI2013"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasWSS6CONF2013conf"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasSYMP2012conf"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasCONF2011symp"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasCONF2011share"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
```


<h4>Poster presentations</h4>

```{r, results='asis', echo=FALSE, eval=TRUE}
print(bib[key = "RamirezCasillasWSS82016poster"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasDiazSimonetICPhS2015poster"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "SimonetCasillasDiazHLS2014poster"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "SimonetCasillasDiazSP72014poster"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
print(bib[key = "CasillasPPLC2013"], .opts = list(check.entries = FALSE, style = "html", bib.style = "authortitle"))
```

</span>
</div> <!-- END FOURTH TAB -->