---
title: "Current projects"
framework: lanyon
onefile: False
mode: selfcontained
url: {lib: ../libraries}
---


### lingreference.org  
  Under development. Created specifically for linguistic terminology, the [lingreference.org][lingreference] database currently contains approx. 0,000 terms, phrases and abbreviations. This dictionary is in no way intended to be exhaustive, but rather is a technical resource specializing in the fields of phonetics, phonology, syntax, and sociolinguistics. The terms included were compiled over the past several years during graduate coursework, as well as taken from journal articles, and books. More info available [here](projects/lingreference).

### R-Snippets  
  This repository is a collection of snippets that I use in [SublimeText] [SublimeText] for doing statistical analysis in [R][R]. The goal is straightforward: document the code that I use most often while doing linguistic research and make it readily available (and understandable) to other linguists. If you are interested in helping, check the [project page](projects/R-snippets). To install R-snippets see the [package control][package control R-snippets] page.

### LaTeX-IPA
  I made this repository to simplify the process of using IPA in LaTeX. It is merely a collection of snippets for the package [TIPA][TIPA]. To install LaTeX-IPA see the [package control][package control LaTeX-IPA] page.

[SublimeText]: http://www.sublimetext.com
[R]: http://www.r-project.org
[TIPA]: http://www.ctan.org/pkg/tipa
[lingreference]: http://www.lingreference.org
[package control R-snippets]: https://sublime.wbond.net/packages/R-snippets
[package control LaTeX-IPA]: https://sublime.wbond.net/packages/LaTeX-IPA
