---
title: "Teaching"
framework: lanyon
onefile: False
mode: selfcontained
url: {lib: ../libraries}
---


Here you can find a list of some of the classes I have taught or am currently teaching, as well as information about some invited talks and specialized workshops I have done. Click on the links for more information about each one.

#### Undergraduate

- University of Arizona
    - [Beginning Spanish (Spanish 101)][101]  
    - [Elementary Spanish (Spanish 102)][102]  
    - [Intermediate Spanish (Spanish 251)][251]  
    - [Introduction to Spanish Phonetics and Phonology (Spanish 340)][340]  
    - [Introduction to Spanish Phonetics and Phonology for the Heritage Speaker (Spanish 343)][343]  
    - [Introduction to Hispanic Linguistics (Spanish 452)][452]  
    - [History of the Spanish Language (Spanish 455)][455]  
    - [Applied Linguistics (Spanish 457)][457]  
- Middlebury College
    - [High Beginner Spanish in Context (Level 1.5)][1.5]
    - [Spanish pronunciation workshop for beginners][clinica]

#### Graduate

- Workshops
    - [Using PsychoPy2 for linguistic research][psychopy]

</br>

[101]: span_101/index.html
[102]: span_102/index.html
[251]: span_251/index.html
[340]: span_340/index.html
[343]: span_343/index.html
[452]: span_452/index.html
[455]: span_455/index.html
[457]: span_457/index.html
[1.5]: span_3151/index.html
[clinica]: span_clinica/index.html
[psychopy]: psychopy/index.html
