---
title: "lingreference.org"
output:
  html_document:
    theme: readable
    highlight: textmate
    include:
      before_body: ../../site_libs/includes/before_body.html
      in_header: ../../site_libs/includes/in_header.html
      after_body: ../../site_libs/includes/after_body.html
    css: ../../site_libs/assets/css/style.css
---


<iframe src="http://ghbtns.com/github-btn.html?user=lingreference&repo=lingreference.github.io&type=watch&count=true&size=large" height="30" width="170" frameborder="0" scrolling="0" style="width:77px; height: 30px;" allowTransparency="true"></iframe>

<iframe src="http://ghbtns.com/github-btn.html?user=lingreference&repo=lingreference.github.io&type=fork&count=true&size=large" height="30" width="170" frameborder="0" scrolling="0" style="width:130px; height: 30px;" allowTransparency="true"></iframe>

<a href="https://twitter.com/lingreference" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @lingreference</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<p></p>

Under development. Created specifically for linguistic terminology, the [lingreference.org](http://www.lingreference.org) database currently contains approx. 0,000 terms, phrases and abbreviations. This dictionary is in no way intended to be exhaustive, but rather is a technical resource specializing in the fields of phonetics, phonology, syntax, and sociolinguistics. The terms included were compiled over the past several years during graduate coursework, as well as taken from journal articles, and books.
