---
config: "../config.yml"
disqus: True
---

### Spanish 343

<strong>Introduction to Spanish Phonetics and Phonology for the Native Speaker</strong>
Spanish 343 is the last course in the Spanish for heritage learners program: 103-203-253-323-333-343. It introduces learners to descriptive linguistics, specifically in the area of phonology and phonetics. Students learn about the differences between spoken and written language and use their new knowledge as the basis to improve their orthography. A main focus in this course is to expose students to the different dialects of the Spanish-speaking world. They particularly enjoy learning to identify similarities and differences between the speech of people from Spanish-speaking countries such as Cuba, Mexico, Spain, or Argentina, to name a few.

<strong>What are the specific objectives of the course?</strong>
By the end of the semester, the student will:

- Identify and describe Spanish sounds
- Identify and describe prosodic features of Spanish
- Identify and analyze basic phonological processes in Spanish
- Identify phonetic and phonological variation among Spanish varieties
- Learn to do phonetic transcriptions
- Utilize their new knowledge to strengthen their spelling skills
