---
title: "Spanish 1.5"
config: "../config.yml"
disqus: True
---


**High Beginner Spanish in Context (Level 1.5)**  

Designed for students with some previous study of Spanish, experience in a Spanish-speaking country, or study of another Romance language, this course builds on and rapidly expands control of basic grammatical structures and vocabulary. Students consolidate their ability to negotiate basic survival situations in the target-language cultures, and prepare themselves for continued study of the language. New language functions will be presented in meaningful activities that emphasize speaking and listening, and that prepare the student for the reading and writing activities of the other High Beginner courses. Cultural knowledge that will build a deeper understanding of how Spanish-speaking peoples communicate is a crucial component of the course content. This course meets two hours a day and is taugh entirely in Spanish.

- [Capítulo 1][Capítulo 1] 
- [Capítulo 2][Capítulo 2] 
- [Capítulo 3][Capítulo 3] 
- [Capítulo 4][Capítulo 4] 
- [Capítulo 5][Capítulo 5] 
- [Capítulo 6][Capítulo 6] 
- [Capítulo 7][Capítulo 7] 
- [Capítulo 8][Capítulo 8] 
- [Capítulo 9][Capítulo 9] 

[Capítulo 1]: cap1.html
[Capítulo 2]: cap2.html
[Capítulo 3]: cap3.html
[Capítulo 4]: cap4.html
[Capítulo 5]: cap5.html
[Capítulo 6]: cap6.html
[Capítulo 7]: cap7.html
[Capítulo 8]: cap8.html
[Capítulo 9]: cap9.html
